(ns inquizitors.registration
  (:require [inquizitors.terminal :as terminal]
            [inquizitors.gamestate :as gamestate]))

; this is a hilariously poor representation. However, as this is the only place it seems logical to have the client render a "view" in the terminal, I can live with it. Anyone with a better idea is still welcome to suggest it!
(def intro-text "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    __    __   __    ______    __  __    __    ______    __    ______   ______    ______    ______    /\\ \\  /\\ \"-.\\ \\  /\\  __ \\  /\\ \\/\\ \\  /\\ \\  /\\___  \\  /\\ \\  /\\__  _\\ /\\  __ \\  /\\  == \\  /\\  ___\\   \\ \\ \\ \\ \\ \\-.  \\ \\ \\ \\/\\_\\ \\ \\ \\_\\ \\ \\ \\ \\ \\/_/  /__ \\ \\ \\ \\/_/\\ \\/ \\ \\ \\/\\ \\ \\ \\  __<  \\ \\___  \\   \\ \\_\\ \\ \\_\\\\\"\\_\\ \\ \\___\\_\\ \\ \\_____\\ \\ \\_\\  /\\_____\\ \\ \\_\\   \\ \\_\\  \\ \\_____\\ \\ \\_\\ \\_\\ \\/\\_____\\   \\/_/  \\/_/ \\/_/  \\/___/_/  \\/_____/  \\/_/  \\/_____/  \\/_/    \\/_/   \\/_____/  \\/_/ /_/  \\/_____/                                                                                                                                                                                                                                                                                                                          IN THE GRIM DARKNESS OF THE FAR FUTURE, THERE IS ONLY TRIVIA.                                                                                                                                                                                                                                                          PLEASE ENTER YOUR NAME BELOW TO BEGIN.                        ")

(defn draw-welcome-screen []
  (terminal/draw-screen intro-text 99))

(defmethod gamestate/on-state-entered :registration []
  (draw-welcome-screen))
